var table = 'gcd_issue';

exports.seed = function(knex, Promise) {
  var rows = Promise.map(issues, function(row) {
    return knex(table).insert(row);
  });
  return Promise.join(
    knex(table).del(),
    rows
  );
};

var issues = [
{
  "id": 17888,
  "number": "1",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "September 1963",
  "key_date": "1963-09-00",
  "sort_code": 43311,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "The on-sale date is the publication date reported in U. S. Copyright Office filings.",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T12:50:33.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "Regular Edition",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "1963-07-02",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 1540651,
  "number": "1",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "September 1963",
  "key_date": "1963-09-00",
  "sort_code": 43312,
  "price": "9d [0-0-9 GBP]",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2016-02-23T11:15:11.000Z",
  "modified": "2016-02-23T11:15:11.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 0,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 0,
  "variant_of_id": 17888,
  "variant_name": "British Price Variant",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 17999,
  "number": "2",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "November 1963",
  "key_date": "1963-11-10",
  "sort_code": 43313,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "The indicia incorrectly has publication listed as monthly when the title is in fact bi-monthly.\r\n\r\nThe on-sale date is the publication date reported in the U. S. Copyright Office filing.",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-24T02:41:09.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "Regular Edition",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "1963-09-03",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 917944,
  "number": "2",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": null,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "November 1963",
  "key_date": "1963-11-00",
  "sort_code": 43314,
  "price": "9d [0-0-9 GBP]",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2012-02-08T00:47:58.000Z",
  "modified": "2016-02-24T02:41:09.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 0,
  "variant_of_id": 17999,
  "variant_name": "British Price Variant",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 18182,
  "number": "3",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "January 1964",
  "key_date": "1964-01-00",
  "sort_code": 43315,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "bi-monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T12:50:57.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 18287,
  "number": "4",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "March 1964",
  "key_date": "1964-03-00",
  "sort_code": 43316,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "bi-monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T11:46:24.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "Regular Edition",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "1964-01-03",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 1540955,
  "number": "4",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "March 1964",
  "key_date": "1964-03-00",
  "sort_code": 43317,
  "price": "9d [0-0-9 GBP]",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "bi-monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2016-02-24T04:32:24.000Z",
  "modified": "2016-02-24T04:32:24.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 0,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 0,
  "variant_of_id": 18287,
  "variant_name": "British Price Variant",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 18386,
  "number": "5",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "May 1964",
  "key_date": "1964-05-00",
  "sort_code": 43318,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "bi-monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T11:53:53.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "Regular Edition",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 1263067,
  "number": "5",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": null,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "May 1964",
  "key_date": "1964-05-00",
  "sort_code": 43319,
  "price": "9d [0-0-9 GBP]",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2014-10-10T16:32:45.000Z",
  "modified": "2016-02-24T04:32:23.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 0,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 0,
  "variant_of_id": 18386,
  "variant_name": "British Price Variant",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 18495,
  "number": "6",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "July 1964",
  "key_date": "1964-07-00",
  "sort_code": 43320,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly, with the exception of December, February, April and June",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T21:08:02.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 18560,
  "number": "7",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "August 1964",
  "key_date": "1964-08-00",
  "sort_code": 43321,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly, with the exception of December, February, April and June",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T12:51:23.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 18616,
  "number": "8",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "September 1964",
  "key_date": "1964-09-00",
  "sort_code": 43322,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly with the exception of December, February, April and June",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T11:54:50.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "Regular Edition",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 1540941,
  "number": "8",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "September 1964",
  "key_date": "1964-09-00",
  "sort_code": 43323,
  "price": "9d [0-0-9 GBP]",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly with the exception of December, February, April and June",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2016-02-24T02:40:01.000Z",
  "modified": "2016-02-24T04:32:23.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 0,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 0,
  "variant_of_id": 18616,
  "variant_name": "British Price Variant",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 18692,
  "number": "9",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "October 1964",
  "key_date": "1964-10-00",
  "sort_code": 43324,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly with the exception of December, February, April and June",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T13:29:26.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 18754,
  "number": "10",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "November 1964",
  "key_date": "1964-11-00",
  "sort_code": 43325,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly with the exception of December, February, April and June",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T13:38:06.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 18821,
  "number": "11",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "December 1964",
  "key_date": "1964-12-00",
  "sort_code": 43326,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T13:28:07.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 18901,
  "number": "12",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "January 1965",
  "key_date": "1965-01-00",
  "sort_code": 43327,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T13:38:49.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 18968,
  "number": "13",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "February 1965",
  "key_date": "1965-02-00",
  "sort_code": 43328,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T13:49:35.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 19034,
  "number": "14",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "March 1965",
  "key_date": "1965-03-00",
  "sort_code": 43329,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T12:50:04.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 19102,
  "number": "15",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "April 1965",
  "key_date": "1965-04-00",
  "sort_code": 43330,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T13:28:37.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 1,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 19164,
  "number": "16",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "May 1965",
  "key_date": "1965-05-00",
  "sort_code": 43331,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T12:58:27.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 19234,
  "number": "17",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "June 1965",
  "key_date": "1965-06-00",
  "sort_code": 43332,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-03-14T01:58:02.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 19301,
  "number": "18",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "July 1965",
  "key_date": "1965-07-00",
  "sort_code": 43333,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T13:29:13.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 19376,
  "number": "19",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 124,
  "no_brand": 0,
  "publication_date": "August 1965",
  "key_date": "1965-08-00",
  "sort_code": 43334,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-25T13:27:42.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 19455,
  "number": "20",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 124,
  "no_brand": 0,
  "publication_date": "September 1965",
  "key_date": "1965-09-10",
  "sort_code": 43335,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-24T04:32:23.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 19534,
  "number": "21",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 124,
  "no_brand": 0,
  "publication_date": "October 1965",
  "key_date": "1965-10-10",
  "sort_code": 43336,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-24T04:32:23.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 19606,
  "number": "22",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 124,
  "no_brand": 0,
  "publication_date": "November 1965",
  "key_date": "1965-11-10",
  "sort_code": 43337,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-03-01T13:26:40.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 19681,
  "number": "23",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "December 1965",
  "key_date": "1965-12-00",
  "sort_code": 43338,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-24T04:33:09.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "Regular Edition",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 1540956,
  "number": "23",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "December 1965",
  "key_date": "1965-12-00",
  "sort_code": 43339,
  "price": "10d [0-0-10 GBP]",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2016-02-24T04:33:09.000Z",
  "modified": "2016-02-24T04:33:09.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 0,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 0,
  "variant_of_id": 19681,
  "variant_name": "British Price Variant",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 19771,
  "number": "24",
  "volume": "1",
  "no_volume": 0,
  "display_volume_with_number": 0,
  "series_id": 1571,
  "indicia_publisher_id": 307,
  "indicia_pub_not_printed": 0,
  "brand_id": 35,
  "no_brand": 0,
  "publication_date": "January 1966",
  "key_date": "1966-01-00",
  "sort_code": 43340,
  "price": "0.12 USD",
  "page_count": 36,
  "page_count_uncertain": 0,
  "indicia_frequency": "monthly",
  "no_indicia_frequency": 0,
  "editing": "Stan Lee",
  "no_editing": 0,
  "notes": "",
  "created": "2001-02-06T05:00:00.000Z",
  "modified": "2016-02-24T04:33:08.000Z",
  "reserved": 0,
  "deleted": 0,
  "is_indexed": 1,
  "isbn": "",
  "valid_isbn": "",
  "no_isbn": 1,
  "variant_of_id": null,
  "variant_name": "Regular Edition",
  "barcode": "",
  "no_barcode": 1,
  "title": "",
  "no_title": 0,
  "on_sale_date": "",
  "on_sale_date_uncertain": 0,
  "rating": "Approved by the Comics Code Authority",
  "no_rating": 0
},
{
  "id": 1171576,
  "number": "6",
  "volume": "",
  "series_id": 75977,
  "indicia_publisher_id": 401,
  "brand_id": 5218,
  "publication_date": "January 2014",
  "key_date": "2014-01-00",
  "price": "5.99 USD",
  "page_count": 68,
  "indicia_frequency": "Monthly except in September and October",
  "variant_name": "Design Variant Cover by Jerome Opeña",
  "barcode": "75960607882000641",
  "on_sale_date": "2013-11-27",
  "rating": "Rated T+"
}];
