var table = 'gcd_series';

exports.seed = function(knex, Promise) {
  var rows = Promise.map(series, function(row) {
    return knex(table).insert(row);
  });
  return Promise.join(
    knex(table).del(),
    rows
  );
};

var series = [
{
    "id": 1571,
    "name": "The Avengers",
    "sort_name": "Avengers",
    "format": "",
    "year_began": 1963,
    "year_began_uncertain": 0,
    "year_ended": 1996,
    "year_ended_uncertain": 0,
    "publication_dates": "September 1963 - September 1996",
    "first_issue_id": 17888,
    "last_issue_id": 1506259,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "Beginning with issue #307 (September 1989) the indicia title drops \"The\" and becomes simply \"Avengers\".",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 402,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2016-02-25T01:39:06.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Silver Age U.S.; later Standard Modern Age U.S.",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "Saddle-stitched (Squarebound #200)",
    "publishing_format": "Was Ongoing Series",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 1807,
    "name": "The Avengers Annual",
    "sort_name": "Avengers Annual",
    "format": "",
    "year_began": 1967,
    "year_began_uncertain": 0,
    "year_ended": 1994,
    "year_ended_uncertain": 0,
    "publication_dates": "September 1967 - 1994",
    "first_issue_id": 21279,
    "last_issue_id": 1509541,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "The indicia for issues #1-4 read just \"The Avengers\". \r\n#1, 2 have \"King-Size Special\" as the logo on the front cover, \"Avengers Special\" in the price box, and \"The Avengers\" in the indicia. \r\n#4 has \"King-Size Special\" as the logo on the front cover, \"Avengers Special\" in the price box, and \"The Avengers\" in the indicia. \r\n#5 has \"The Mighty Avengers Special\" as the logo, \"Avengers Special\" in the price box, and \"The Avengers\" in the indicia.\r\nBy issue #6 it has \"King-Size Annual\" as the logo on the front cover, \"Avengers Annual\" in the price box, and \"The Avengers Annual\" in the indicia. (per Michel Faber June 16, 2006).",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 23,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2015-12-11T07:41:32.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "color",
    "dimensions": "standard Silver Age U.S.; standard Modern Age U.S.",
    "paper_stock": "glossy cover; newsprint interior",
    "binding": "squarebound (#1-9, 17-23); saddle-stitched (#10-16)",
    "publishing_format": "was ongoing series",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 2163,
    "name": "Giant-Size Avengers",
    "sort_name": "Giant-Size Avengers",
    "format": "",
    "year_began": 1974,
    "year_began_uncertain": 0,
    "year_ended": 1975,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 27642,
    "last_issue_id": 29365,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 5,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2015-04-01T13:02:25.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 0,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "color",
    "dimensions": "Standard Modern Age U.S.",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "squarebound",
    "publishing_format": "was ongoing series",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 2747,
    "name": "The Kree-Skrull War Starring the Avengers",
    "sort_name": "Kree-Skrull War Starring the Avengers",
    "format": "",
    "year_began": 1983,
    "year_began_uncertain": 0,
    "year_ended": 1984,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 37777,
    "last_issue_id": 37868,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "Reprints of Avengers stories",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 2,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2014-06-16T19:58:49.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "Glossy cover; Baxter interior",
    "binding": "Saddle-stitched",
    "publishing_format": "Limited Series",
    "has_rating": 0,
    "publication_type_id": null,
    "is_singleton": 0
},
{
    "id": 2900,
    "name": "West Coast Avengers",
    "sort_name": "West Coast Avengers",
    "format": "",
    "year_began": 1984,
    "year_began_uncertain": 0,
    "year_ended": 1984,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 39113,
    "last_issue_id": 955983,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 4,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2013-12-23T09:16:42.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "Saddle-stitched",
    "publishing_format": "Limited Series",
    "has_rating": 0,
    "publication_type_id": null,
    "is_singleton": 0
},
{
    "id": 3061,
    "name": "West Coast Avengers",
    "sort_name": "West Coast Avengers",
    "format": "",
    "year_began": 1985,
    "year_began_uncertain": 0,
    "year_ended": 1989,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 40564,
    "last_issue_id": 870723,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 47,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2015-08-08T22:35:20.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "color",
    "dimensions": "standard Modern Age US",
    "paper_stock": "glossy cover; newsprint interior",
    "binding": "saddle-stitched",
    "publishing_format": "was ongoing series",
    "has_rating": 0,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 3208,
    "name": "The West Coast Avengers Annual",
    "sort_name": "West Coast Avengers Annual",
    "format": "",
    "year_began": 1986,
    "year_began_uncertain": 0,
    "year_ended": 1989,
    "year_ended_uncertain": 0,
    "publication_dates": "1986 - 1989",
    "first_issue_id": 40849,
    "last_issue_id": 1035843,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 4,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2015-07-11T14:17:09.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U.S.",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "Saddle-stitched",
    "publishing_format": "Was Ongoing Series",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 3435,
    "name": "Solo Avengers",
    "sort_name": "Solo Avengers",
    "format": "",
    "year_began": 1987,
    "year_began_uncertain": 0,
    "year_ended": 1989,
    "year_ended_uncertain": 0,
    "publication_dates": "December 1987 - July 1989",
    "first_issue_id": 43741,
    "last_issue_id": 46490,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 20,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2015-02-22T23:11:52.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age US",
    "paper_stock": "Glossy Cover; Newsprint Interior",
    "binding": "Saddle-stitched",
    "publishing_format": "Was ongoing",
    "has_rating": 0,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 3443,
    "name": "The X-Men vs. The Avengers",
    "sort_name": "X-Men vs. The Avengers",
    "format": "",
    "year_began": 1987,
    "year_began_uncertain": 0,
    "year_ended": 1987,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 42767,
    "last_issue_id": 1137413,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "Both the Avengers and the Soviet Super Soldiers want Magneto. The X-Men try to save him.\r\n\r\nThe team line-ups are circa The Avengers (Marvel, 1963 series) #290 and The Uncanny X-Men (Marvel, 1981 series) #212.",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 4,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2013-08-17T19:10:36.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "Saddle-stitched",
    "publishing_format": "Limited Series",
    "has_rating": 0,
    "publication_type_id": null,
    "is_singleton": 0
},
{
    "id": 3748,
    "name": "Scavengers",
    "sort_name": "Scavengers",
    "format": "",
    "year_began": 1988,
    "year_began_uncertain": 0,
    "year_ended": 1989,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 43995,
    "last_issue_id": 953222,
    "is_current": 0,
    "publisher_id": 517,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "Killer beastie stories reprinted from Britain's weekly 2000 AD magazine. Also scattered throughout the books are numerous uncredited pinups (probably done by the story artists).\r\n\r\nThe UK editions of this title continue the numbering of Spellbinders (Fleetway/Quality, 1987 series), while the US editions of this title start over with #1.",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 27,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2015-06-03T18:18:14.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "",
    "paper_stock": "",
    "binding": "",
    "publishing_format": "",
    "has_rating": 0,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 3829,
    "name": "Avengers Spotlight",
    "sort_name": "Avengers Spotlight",
    "format": "",
    "year_began": 1989,
    "year_began_uncertain": 0,
    "year_ended": 1991,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 46591,
    "last_issue_id": 49116,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 20,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2015-02-22T23:12:06.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 1,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "Saddle-stitched",
    "publishing_format": "Was Ongoing Series",
    "has_rating": 0,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 3830,
    "name": "Avengers West Coast",
    "sort_name": "Avengers West Coast",
    "format": "",
    "year_began": 1989,
    "year_began_uncertain": 0,
    "year_ended": 1994,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 46720,
    "last_issue_id": 863573,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 55,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2015-02-22T22:47:19.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "color",
    "dimensions": "standard Modern Age US",
    "paper_stock": "glossy cover; newsprint interior",
    "binding": "saddle-stitched",
    "publishing_format": "was ongoing series",
    "has_rating": 0,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 3831,
    "name": "Avengers West Coast Annual",
    "sort_name": "Avengers West Coast Annual",
    "format": "",
    "year_began": 1990,
    "year_began_uncertain": 0,
    "year_ended": 1993,
    "year_ended_uncertain": 0,
    "publication_dates": "1990 - 1993",
    "first_issue_id": 48455,
    "last_issue_id": 1036285,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 4,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2015-02-23T00:04:09.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U.S.",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "Squarebound",
    "publishing_format": "Annual",
    "has_rating": 0,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 4225,
    "name": "Avengers: Death Trap, The Vault",
    "sort_name": "Avengers: Death Trap, The Vault",
    "format": "",
    "year_began": 1991,
    "year_began_uncertain": 0,
    "year_ended": 1991,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 48945,
    "last_issue_id": 48945,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 1,
    "created": "2000-06-03T04:00:00.000Z",
    "modified": "2015-03-05T23:31:07.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 0,
    "has_isbn": 1,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 0,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "8.25\" x 10.75\"",
    "paper_stock": "Cardstock cover; Glossy interior",
    "binding": "Squarebound",
    "publishing_format": "One-shot",
    "has_rating": 0,
    "publication_type_id": 2,
    "is_singleton": 1
},
{
    "id": 4668,
    "name": "Avengers: The Terminatrix Objective",
    "sort_name": "Avengers: The Terminatrix Objective",
    "format": "",
    "year_began": 1993,
    "year_began_uncertain": 0,
    "year_ended": 1993,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 53627,
    "last_issue_id": 1509600,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 4,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2015-12-12T06:38:34.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "Glossy cover (Cardstock cover #1); Newsprint interior",
    "binding": "Saddle-stitched",
    "publishing_format": "Limited Series",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 5275,
    "name": "Avengers Unplugged",
    "sort_name": "Avengers Unplugged",
    "format": "",
    "year_began": 1995,
    "year_began_uncertain": 0,
    "year_ended": 1996,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 57834,
    "last_issue_id": 1510043,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 6,
    "created": "1999-12-31T05:00:00.000Z",
    "modified": "2015-12-14T00:33:00.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "Saddle-stitched",
    "publishing_format": "Was Ongoing Series",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 5540,
    "name": "Avengers: Timeslide",
    "sort_name": "Avengers: Timeslide",
    "format": "",
    "year_began": 1996,
    "year_began_uncertain": 0,
    "year_ended": 1996,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 58458,
    "last_issue_id": 58458,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 1,
    "created": "1999-04-10T04:00:00.000Z",
    "modified": "2015-12-13T13:27:50.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "Cardstock Foil cover; Glossy interior",
    "binding": "Saddle-stitched",
    "publishing_format": "One-Shot",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 1
},
{
    "id": 6180,
    "name": "Avengers United They Stand",
    "sort_name": "Avengers United They Stand",
    "format": "",
    "year_began": 1999,
    "year_began_uncertain": 0,
    "year_ended": 2000,
    "year_ended_uncertain": 0,
    "publication_dates": "November 1999 - June 2000",
    "first_issue_id": 63026,
    "last_issue_id": 63305,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "Tie-in to the animated series of the same name.",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 7,
    "created": "2000-06-04T04:00:00.000Z",
    "modified": "2013-11-27T08:25:14.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 1,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "Newsprint",
    "binding": "Saddle-stitched",
    "publishing_format": "",
    "has_rating": 0,
    "publication_type_id": null,
    "is_singleton": 0
},
{
    "id": 6288,
    "name": "Avengers: Casebook 1999",
    "sort_name": "Avengers: Casebook 1999",
    "format": "",
    "year_began": 2000,
    "year_began_uncertain": 0,
    "year_ended": 2000,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 63193,
    "last_issue_id": 63193,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 1,
    "created": "2000-06-04T04:00:00.000Z",
    "modified": "2013-11-27T21:42:53.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 1,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "",
    "binding": "",
    "publishing_format": "One-Shot",
    "has_rating": 0,
    "publication_type_id": null,
    "is_singleton": 0
},
{
    "id": 7239,
    "name": "Avengers Infinity",
    "sort_name": "Avengers Infinity",
    "format": "",
    "year_began": 2000,
    "year_began_uncertain": 0,
    "year_ended": 2000,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 65315,
    "last_issue_id": 65318,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 4,
    "created": "2001-10-27T04:00:00.000Z",
    "modified": "2015-12-11T06:15:16.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "Saddle-stitched",
    "publishing_format": "Limited Series",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 7252,
    "name": "Avengers",
    "sort_name": "Avengers",
    "format": "",
    "year_began": 1996,
    "year_began_uncertain": 0,
    "year_ended": 1997,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 65395,
    "last_issue_id": 1508236,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "\"Heroes Reborn\" series\r\nIndicia \"Avengers\", cover title \"the Avengers\"\r\nReferred to as \"Heroes Reborn Universe\" or \"Counter-Earth\".",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 13,
    "created": "2001-10-27T04:00:00.000Z",
    "modified": "2015-12-03T06:11:01.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age US",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "Saddle-Stitched",
    "publishing_format": "Was Ongoing Series",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 7630,
    "name": "Avengers",
    "sort_name": "Avengers",
    "format": "",
    "year_began": 1999,
    "year_began_uncertain": 0,
    "year_ended": 1999,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 68283,
    "last_issue_id": 68283,
    "is_current": 0,
    "publisher_id": 1133,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 1,
    "created": "2004-03-04T05:00:00.000Z",
    "modified": "2013-09-10T20:10:43.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age US",
    "paper_stock": "",
    "binding": "Saddle-stitched",
    "publishing_format": "Supplement",
    "has_rating": 0,
    "publication_type_id": null,
    "is_singleton": 0
},
{
    "id": 7631,
    "name": "Avengers / Squadron Supreme '98",
    "sort_name": "Avengers / Squadron Supreme '98",
    "format": "",
    "year_began": 1998,
    "year_began_uncertain": 0,
    "year_ended": 1998,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 68284,
    "last_issue_id": 68284,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 1,
    "created": "2004-03-04T05:00:00.000Z",
    "modified": "2015-11-05T20:37:05.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age US",
    "paper_stock": "",
    "binding": "Saddle-stitched",
    "publishing_format": "One-shot",
    "has_rating": 0,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 7632,
    "name": "Avengers 1999",
    "sort_name": "Avengers 1999",
    "format": "",
    "year_began": 1999,
    "year_began_uncertain": 0,
    "year_ended": 1999,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 68285,
    "last_issue_id": 68285,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 1,
    "created": "2004-03-04T05:00:00.000Z",
    "modified": "2015-12-10T23:46:49.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age US",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "Saddle-stitched",
    "publishing_format": "One-shot",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 7633,
    "name": "Avengers 2000",
    "sort_name": "Avengers 2000",
    "format": "",
    "year_began": 2000,
    "year_began_uncertain": 0,
    "year_ended": 2000,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 68286,
    "last_issue_id": 68286,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 1,
    "created": "2004-03-04T05:00:00.000Z",
    "modified": "2015-12-10T23:46:59.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age US",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "Saddle-stitched",
    "publishing_format": "One-shot",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 7634,
    "name": "Avengers 2001",
    "sort_name": "Avengers 2001",
    "format": "",
    "year_began": 2001,
    "year_began_uncertain": 0,
    "year_ended": 2001,
    "year_ended_uncertain": 0,
    "publication_dates": "[September] 2001",
    "first_issue_id": 68287,
    "last_issue_id": 68287,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "Last AVENGERS annual.",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 1,
    "created": "2004-03-04T05:00:00.000Z",
    "modified": "2015-07-11T14:17:34.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 0,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "Newsprint",
    "binding": "Saddle-stitched",
    "publishing_format": "One-Shot",
    "has_rating": 0,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 7635,
    "name": "Avengers: The Ultron Imperative",
    "sort_name": "Avengers: The Ultron Imperative",
    "format": "",
    "year_began": 2001,
    "year_began_uncertain": 0,
    "year_ended": 2001,
    "year_ended_uncertain": 0,
    "publication_dates": "November 2001",
    "first_issue_id": 68288,
    "last_issue_id": 68288,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 1,
    "created": "2004-03-04T05:00:00.000Z",
    "modified": "2013-11-28T06:40:49.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 1,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "Newsprint",
    "binding": "Saddle-stitched",
    "publishing_format": "One-Shot",
    "has_rating": 0,
    "publication_type_id": null,
    "is_singleton": 0
},
{
    "id": 7636,
    "name": "Avengers",
    "sort_name": "Avengers",
    "format": "",
    "year_began": 1998,
    "year_began_uncertain": 0,
    "year_ended": 2004,
    "year_ended_uncertain": 0,
    "publication_dates": "February 1998 - August 2004",
    "first_issue_id": 68289,
    "last_issue_id": 1508937,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "Renumbering at #500 based on the following previous issues:\r\nThe Avengers (Marvel, 1963 series) - 402 issues\r\nAvengers (Marvel, 1996 series) - 13 issues\r\nAvengers (Marvel, 1998 series) [this series] - 84 issues\r\n\r\nIndicia \"Avengers\", cover title \"the Avengers\"\r\n\r\nVolume 3.\r\n\r\nStory continues in Avengers Finale (Marvel, 2004 series).",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 89,
    "created": "2004-03-04T05:00:00.000Z",
    "modified": "2015-12-07T15:55:52.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "color",
    "dimensions": "standard modern Age US",
    "paper_stock": "Glossy cover; Newsprint interior (1-52); Glossy interior (53-503)",
    "binding": "saddle-stitched",
    "publishing_format": "Was ongoing",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 7830,
    "name": "Avengers Two: Wonder Man & Beast",
    "sort_name": "Avengers Two: Wonder Man & Beast",
    "format": "",
    "year_began": 2000,
    "year_began_uncertain": 0,
    "year_ended": 2000,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 69288,
    "last_issue_id": 69290,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "Cover title \"Avengers Two: Wonder Man & the Beast\"",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 3,
    "created": "2002-03-24T05:00:00.000Z",
    "modified": "2015-12-13T13:57:37.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 0,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "Glossy cover; Newsprint interior",
    "binding": "Saddle-Stitched",
    "publishing_format": "Miniseries",
    "has_rating": 1,
    "publication_type_id": 2,
    "is_singleton": 0
},
{
    "id": 9805,
    "name": "Avengers Log",
    "sort_name": "Avengers Log",
    "format": "",
    "year_began": 1994,
    "year_began_uncertain": 0,
    "year_ended": 1994,
    "year_ended_uncertain": 0,
    "publication_dates": "",
    "first_issue_id": 83418,
    "last_issue_id": 83418,
    "is_current": 0,
    "publisher_id": 78,
    "country_id": 225,
    "language_id": 25,
    "tracking_notes": "",
    "notes": "",
    "publication_notes": "",
    "has_gallery": 1,
    "open_reserve": 0,
    "issue_count": 1,
    "created": "2004-03-04T05:00:00.000Z",
    "modified": "2013-11-27T08:24:56.000Z",
    "reserved": 0,
    "deleted": 0,
    "has_indicia_frequency": 1,
    "has_isbn": 1,
    "has_barcode": 1,
    "has_issue_title": 0,
    "has_volume": 1,
    "is_comics_publication": 1,
    "color": "Color",
    "dimensions": "Standard Modern Age U. S.",
    "paper_stock": "",
    "binding": "",
    "publishing_format": "One-Shot",
    "has_rating": 0,
    "publication_type_id": null,
    "is_singleton": 0
}];
